### ISSUE TITLE
NoMethodError: undefined method `alias_method_chain'

### ISSUE THREAD

**Issue by n0rvik** [HugoHasenbein/redmine_tint_issues#1]
Hi

I get an error while running the command:

```
[~/redmine]$ bundle exec rake redmine:plugins:migrate NAME=redmine_tint_issues RAILS_ENV=production
rake aborted!
NoMethodError: undefined method `alias_method_chain' for #<Class:0x00000000051b2038>
Did you mean?  alias_method
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activerecord-5.2.4.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
/mnt/storage/opt/redmine/redmine/plugins/redmine_tint_issues/lib/redmine_tint_issues/patches/issue_patch.rb:31:in `block in included'
/mnt/storage/opt/redmine/redmine/plugins/redmine_tint_issues/lib/redmine_tint_issues/patches/issue_patch.rb:29:in `class_eval'
/mnt/storage/opt/redmine/redmine/plugins/redmine_tint_issues/lib/redmine_tint_issues/patches/issue_patch.rb:29:in `included'
/mnt/storage/opt/redmine/redmine/plugins/redmine_tint_issues/lib/redmine_tint_issues/patches/issue_patch.rb:244:in `include'
/mnt/storage/opt/redmine/redmine/plugins/redmine_tint_issues/lib/redmine_tint_issues/patches/issue_patch.rb:244:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
/mnt/storage/opt/redmine/redmine/plugins/redmine_tint_issues/lib/redmine_tint_issues.rb:22:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
/mnt/storage/opt/redmine/redmine/plugins/redmine_tint_issues/init.rb:41:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `block in require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:291:in `require'
/mnt/storage/opt/redmine/redmine/lib/redmine/plugin.rb:181:in `block in load'
/mnt/storage/opt/redmine/redmine/lib/redmine/plugin.rb:172:in `each'
/mnt/storage/opt/redmine/redmine/lib/redmine/plugin.rb:172:in `load'
/mnt/storage/opt/redmine/redmine/config/initializers/30-redmine.rb:20:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `block in load'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:257:in `load_dependency'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/dependencies.rb:285:in `load'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:663:in `block in load_config_initializer'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/activesupport-5.2.4.1/lib/active_support/notifications.rb:170:in `instrument'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:662:in `load_config_initializer'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `each'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/engine.rb:619:in `block in <class:Engine>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `instance_exec'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:32:in `run'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `each'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/initializable.rb:60:in `run_initializers'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/application.rb:361:in `initialize!'
/mnt/storage/opt/redmine/redmine/config/environment.rb:16:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/application.rb:337:in `require_environment!'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/railties-5.2.4.1/lib/rails/application.rb:520:in `block in run_tasks_blocks'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/mnt/storage/opt/redmine/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```
```
Environment:
  Redmine version                4.1.0.stable
  Ruby version                   2.6.3-p62 (2019-04-16) [x86_64-linux]
  Rails version                  5.2.4.1
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.7.14
  Mercurial                      5.2.2
  Bazaar                         2.5.1
  Git                            2.9.3
  Filesystem                     
  Xitolite                       2.9.3
Redmine plugins:
  additionals                    2.0.23
  progressive_projects_list      4.0.0
  redmine_git_hosting            4.0.1
  redmine_issue_badge            0.1.3
  redmine_tags                   4.0.0
  ```

**Comment by HugoHasenbein** [comment]
This was an issue related to the abanonement of some macros in Rails 5+: the issue is now solved
