### ISSUE TITLE
not work in redmine 5.0 ruby 3.0.3

### ISSUE THREAD

**Issue by ashrafalzyoud** [HugoHasenbein/redmine_tint_issues#9]
```
expected file /home/redmine/5.0/plugins/redmine_tint_issues/lib/redmine_tint_issues/hooks/hooks_views.rb to define constant RedmineTintIssues::Hooks::HooksViews, but didn't (Zeitwerk::NameError)
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/kernel.rb:28:in `require'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `const_get'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:95:in `cget'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:237:in `block (2 levels) in eager_load'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:26:in `block in ls'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `each_child'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/helpers.rb:18:in `ls'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:232:in `block in eager_load'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `synchronize'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:217:in `eager_load'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `each'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/zeitwerk-2.5.4/lib/zeitwerk/loader.rb:317:in `eager_load_all'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-6.1.6/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `each'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `call'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'
  /home/redmine/5.0/config/environment.rb:16:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:125:in `instance_eval'
  /home/redmine/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/rack-2.2.3.1/lib/rack/builder.rb:125:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:397:in `run_block_and_record_step_progress'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'

```

**Comment by HugoHasenbein** [comment]
just delete
> /home/redmine/5.0/plugins/redmine_tint_issues/lib/redmine_tint_issues/hooks/hooks_views.rb
its in only for historical reasons

it is deleted now in git
